Update advanced-configuration.html
mail-in-a-box/mailinabox.email pull request #77
Opened 2020-11-29 02:41 UTC by kingwarrick

to include information about reverse proxy.

2020-11-29 13:55 UTC, kingwarrick commented
Updated with additional instructions to trigger reload

2020-12-25 02:16 UTC, JoshData requested changes

2020-12-25 02:16 UTC, JoshData commented on advanced-configuration.html
> +					<h2>MiaB as Reverse Proxy</h2>
The "MiaB" abbreviation isn't used in our documentation. Spell it out as "Mail-in-a-Box".

2020-12-25 02:16 UTC, JoshData commented on advanced-configuration.html
> +					<p>If you are running multiple services on the same IP address as your Mail-in-a-Box server, you can use nginx within MiaB to proxy to those services. By editing <code>/home/user-data/www/custom
Same here.

2020-12-25 02:16 UTC, JoshData commented on advanced-configuration.html
> +					<p>If you are running multiple services on the same IP address as your Mail-in-a-Box server, you can use nginx within MiaB to proxy to those services. By editing <code>/home/user-data/www/custom
This isn't limited to services on the same IP address.

2020-12-25 02:16 UTC, JoshData commented on advanced-configuration.html
> +					<p>See https://github.com/mail-in-a-box/mailinabox/issues/608#issuecomment-279204357 for more discussion and use cases</p>
The URL should be a HTML link. There should be a period at the end of the sentence.

2023-01-21 13:26 UTC, closed without merging