rename ubuntu 18.04 -> 22.04
mail-in-a-box/mailinabox.email pull request #94
Opened 2022-10-19 01:41 UTC by SConaway

When migrating to v60 running on ubuntu 22.04, I noticed that a lot of the docs still referred to MIAB as running on 18.04. I thought I'd change the docs to reflect the changes.

2022-10-20 09:39 UTC, JoshData requested changes
Thanks, but some of these are correct - see comments.

2022-10-20 09:39 UTC, JoshData commented on maintenance.html
> +	    				<p>1. Follow the instructions in this section to upgrade your existing Mail-in-a-Box to the latest version supporting Ubuntu 22.04.</p>
These two lines should be reverted.

2022-10-20 09:39 UTC, JoshData commented on maintenance.html
> +	    			<p>If you want to move your Mail-in-a-Box installation to a new machine (e.g. you&rsquo;re getting more memory, getting a new IP address, etc.), or if something is horribly wrong with your bo
This one too.

2022-10-20 09:39 UTC, JoshData commented on maintenance.html
> +	    				If you are upgrading from Mail-in-a-Box version v0.50 or earlier on <strong>Ubuntu 22.04</strong> to version 60 or later on <strong>Ubuntu 22.04</strong>, you must follow the instructions in
This one too, except for the typo that you fixed.

2022-10-20 16:32 UTC, SConaway commented
Oh goodness, yes! I did not read those changes well enough. Will fix by end of day.

2022-10-21 02:32 UTC, SConaway commented
Ok, super sorry about that. Should be fixed now

2022-10-21 22:58 UTC, merged

2022-10-21 22:58 UTC, JoshData commented
Thanks!